/*
 * Copyright 2026 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.google.android.horologist.remotecompose.lottie

import com.google.common.truth.Truth.assertThat
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import org.junit.Ignore
import org.junit.Test

/** Reference geometry is generated by pinned Lottie-web, not by the Kotlin offset modifier. */
class OffsetTopologyTest : MotionPixelHarness() {
  @Test
  fun orderedReferenceRetainsOriginalStarFrame() {
    val root =
      Json.parseToJsonElement(
          checkNotNull(javaClass.getResource("/offset-topology-reference.json")).readText()
        )
        .jsonObject
    assertThat(root.getValue("intersectionOrder").jsonPrimitive.content).isEqualTo("ascending-t")
    assertThat(root.getValue("originalOrderRetained").jsonPrimitive.content)
      .isEqualTo("webExpected")
    val cases = root.getValue("cases").jsonArray.map { it.jsonObject }
    for (case in cases) for (frame in case.getValue("frames").jsonArray) {
      assertThat(frame.jsonObject.containsKey("webExpected")).isTrue()
    }
    val frame =
      cases
        .single { it.getValue("name").jsonPrimitive.content == "rounded-star" }
        .getValue("frames")
        .jsonArray[6]
        .jsonObject
    assertThat(frame.getValue("expected")).isNotEqualTo(frame.getValue("webExpected"))
  }

  @Ignore("TODO: Fix failure on main AST/renderer")
  @Test
  fun polygonPointCount() = verify("polygon")

  @Ignore("TODO: Fix failure on main AST/renderer")
  @Test
  fun roundedPolygonPointCount() = verify("rounded-polygon")

  @Ignore("TODO: Fix failure on main AST/renderer")
  @Test
  fun roundedPolygonSevenPointControl() = verify("rounded-polygon", static = true, staticFrame = 10)

  @Ignore("TODO: Fix failure on main AST/renderer")
  @Test
  fun roundedStarPointCount() = verify("rounded-star")

  @Ignore("TODO: Fix failure on main AST/renderer")
  @Test
  fun roundedStarStaticControl() = verify("rounded-star", static = true)

  @Ignore("TODO: Fix failure on main AST/renderer")
  @Test
  fun roundedStarSevenPointControl() = verify("rounded-star", static = true, staticFrame = 10)

  @Ignore("TODO: Fix failure on main AST/renderer")
  @Test
  fun roundedStarFractionalControl() = verify("rounded-star", static = true, staticFrame = 1)

  @Ignore("TODO: Fix failure on main AST/renderer")
  @Test
  fun roundedStarFivePointFourControl() = verify("rounded-star", static = true, staticFrame = 6)

  @Ignore("TODO: Fix failure on main AST/renderer")
  @Test
  fun roundedCornerActivation() = verify("rounded-corners")

  @Ignore("TODO: Fix failure on main AST/renderer")
  @Test
  fun splitGroupStaticCrossing() = verifySplitPrune(false, false)

  @Ignore("TODO: Fix failure on main AST/renderer")
  @Test
  fun splitGroupLiveCrossing() = verifySplitPrune(true, false)

  @Ignore("TODO: Fix failure on main AST/renderer")
  @Test
  fun paddedSplitGroupStaticCrossing() = verifySplitPrune(false, true)

  @Ignore("TODO: Fix failure on main AST/renderer")
  @Test
  fun paddedSplitGroupLiveCrossing() = verifySplitPrune(true, true)

  @Ignore("TODO: Fix failure on main AST/renderer")
  @Test
  fun splitGroupAnimatedAmount() = verifySplitAmount("amount", false)

  @Ignore("TODO: Fix failure on main AST/renderer")
  @Test
  fun paddedSplitGroupAnimatedAmount() = verifySplitAmount("amount", true)

  @Ignore("TODO: Fix failure on main AST/renderer")
  @Test
  fun splitGroupSignedAmount() = verifySplitAmount("signed", false)

  @Ignore("TODO: Fix failure on main AST/renderer")
  @Test
  fun paddedSplitGroupSignedAmount() = verifySplitAmount("signed", true)

  private fun verifySplitAmount(kind: String, padded: Boolean) {
    val fixture =
      Json.parseToJsonElement(
          checkNotNull(javaClass.getResource("/offset-topology-reference.json")).readText()
        )
        .jsonObject
        .getValue("cases")
        .jsonArray
        .map { it.jsonObject }
        .single { it.getValue("name").jsonPrimitive.content == "split-prune-$kind" }
    val source = fixture.getValue("input").jsonArray.single().toString()
    val rounding = if (padded) """,{"ty":"rd","r":${fixed("1")}}""" else ""
    val offset = """{"ty":"op","a":${fixture.getValue("amount")},"lj":1,"ml":${fixed("100")}}"""
    val stroke =
      """{"ty":"st","c":${fixed("[1,0,0,1]")},"o":${fixed("100")},"w":${fixed("2")},"lc":1,"lj":1,"ml":100}"""
    assertMatchesStaticFrames(
      animation("$source$rounding,$offset,$stroke"),
      referenceProbeAt = { Probe(32, 32, 1f, 1f) },
      artifactName = "offset-topology-split-prune-$kind${if (padded) "-padded" else ""}",
      frames = (0..10).toList() + listOf(5, 0, 10, 0, 5),
      maxMeanRedError = .0002f,
      maxPeakRedError = .3f,
      staticAt = { frame ->
        val path = fixture.getValue("frames").jsonArray[frame].jsonObject.getValue("expected")
        animation("""{"ty":"sh","ks":${fixed(path.toString())}},$stroke""")
      },
    )
  }

  private fun verifySplitPrune(dynamic: Boolean, padded: Boolean) {
    val fixture =
      Json.parseToJsonElement(
          checkNotNull(javaClass.getResource("/offset-topology-reference.json")).readText()
        )
        .jsonObject
        .getValue("cases")
        .jsonArray
        .map { it.jsonObject }
        .single { it.getValue("name").jsonPrimitive.content == "split-prune" }
    val frames = fixture.getValue("frames").jsonArray
    val source =
      if (dynamic) fixture.getValue("input").jsonArray.single().toString()
      else """{"ty":"sh","ks":${fixed(frames[0].jsonObject.getValue("source").toString())}}"""
    // Every vertex already has handles: rounding changes no geometry, but adds logical padding.
    val rounding = if (padded) """,{"ty":"rd","r":${fixed("1")}}""" else ""
    val offset = """{"ty":"op","a":${fixed("4")},"lj":1,"ml":${fixed("100")}}"""
    val stroke =
      """{"ty":"st","c":${fixed("[1,0,0,1]")},"o":${fixed("100")},"w":${fixed("2")},"lc":1,"lj":1,"ml":100}"""
    assertMatchesStaticFrames(
      animation("$source$rounding,$offset,$stroke"),
      referenceProbeAt = { Probe(32, 32, 1f, 1f) },
      artifactName =
        "offset-topology-split-prune${if (padded) "-padded" else ""}${if (dynamic) "" else "-static"}",
      frames = if (dynamic) (0..10).toList() + listOf(5, 0, 0) else listOf(0),
      maxMeanRedError = .0002f,
      maxPeakRedError = .3f,
      staticAt = { frame ->
        val path = frames[frame].jsonObject.getValue("expected")
        animation("""{"ty":"sh","ks":${fixed(path.toString())}},$stroke""")
      },
    )
  }

  private fun verify(name: String, static: Boolean = false, staticFrame: Int = 0) {
    val fixture =
      Json.parseToJsonElement(
          checkNotNull(javaClass.getResource("/offset-topology-reference.json")).readText()
        )
        .jsonObject
        .getValue("cases")
        .jsonArray
        .map { it.jsonObject }
        .single { it.getValue("name").jsonPrimitive.content == name }
    val shapes =
      fixture.getValue("input").jsonArray.joinToString(",") {
        if (static)
          JsonObject(
              it.jsonObject +
                ("pt" to Json.parseToJsonElement(fixed((3f + staticFrame * 0.4f).toString())))
            )
            .toString()
        else it.toString()
      }
    val offset = """{"ty":"op","a":${fixed("2")},"lj":1,"ml":${fixed("100")}}"""
    val stroke =
      """{"ty":"st","c":${fixed("[1,0,0,1]")},"o":${fixed("100")},"w":${fixed("2")},"lc":1,"lj":1,"ml":100}"""
    assertMatchesStaticFrames(
      animation("$shapes,$offset,$stroke"),
      referenceProbeAt = { Probe(32, 32, 1f, 1f) },
      artifactName =
        "offset-topology-$name${if (static) "-static${if (staticFrame == 0) "" else "-$staticFrame"}" else ""}",
      frames = if (static) listOf(staticFrame) else (0..10).toList() + listOf(5, 0, 0),
      maxMeanRedError = 0.0002f,
      maxPeakRedError = 0.3f,
      staticAt = { frame ->
        val path = fixture.getValue("frames").jsonArray[frame].jsonObject.getValue("expected")
        animation("""{"ty":"sh","ks":${fixed(path.toString())}},$stroke""")
      },
    )
  }
}
