name: Fixups

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fixes:
    runs-on: ubuntu-latest
    timeout-minutes: 40

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          lfs: 'true'

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: set up JDK
        uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # v5
        with:
          distribution: 'zulu'
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@9c971963bec38e04b3d30dcc455b5382be2fdbfb # v6

      - name: Reformat
        run: ./gradlew --continue ktfmtFormat

      - name: Push reformatted code
        uses: stefanzweifel/git-auto-commit-action@4a55954c782fc1ea30b9056cd3e7a2b40ca8887d # v7
        with:
          file_pattern: '**/*.kt'
          disable_globbing: true
          commit_message: "🤖 reformat"

      - name: Generate APIs
        run: ./gradlew --continue metalavaGenerateSignature metalavaGenerateSignatureRelease

      - name: Push new apis
        uses: stefanzweifel/git-auto-commit-action@4a55954c782fc1ea30b9056cd3e7a2b40ca8887d # v7
        with:
          file_pattern: '**/current.api'
          disable_globbing: true
          commit_message: "🤖 metalava"

      - name: Repair screenshots
        run: ./gradlew --continue verifyAndRecordRoborazziDebug

      - name: Push new screenshots if available
        uses: stefanzweifel/git-auto-commit-action@4a55954c782fc1ea30b9056cd3e7a2b40ca8887d # v7
        if: ${{ always() }}
        with:
          file_pattern: '**/snapshots/images/*.png **/screenshots/*.png **/audit/*.png'
          disable_globbing: true
          commit_message: "🤖 Updates screenshots"
